/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UplinkRouteImport } from './routes/uplink'
import { Route as StatusRouteImport } from './routes/status'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const UplinkRoute = UplinkRouteImport.update({
  id: '/uplink',
  path: '/uplink',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/integrations': typeof IntegrationsRoute
  '/legal': typeof LegalRoute
  '/onboard': typeof OnboardRoute
  '/status': typeof StatusRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/integrations': typeof IntegrationsRoute
  '/legal': typeof LegalRoute
  '/onboard': typeof OnboardRoute
  '/status': typeof StatusRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/integrations': typeof IntegrationsRoute
  '/legal': typeof LegalRoute
  '/onboard': typeof OnboardRoute
  '/status': typeof StatusRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/architecture'
    | '/callback'
    | '/dashboard'
    | '/discover'
    | '/integrations'
    | '/legal'
    | '/onboard'
    | '/status'
    | '/uplink'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/architecture'
    | '/callback'
    | '/dashboard'
    | '/discover'
    | '/integrations'
    | '/legal'
    | '/onboard'
    | '/status'
    | '/uplink'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/architecture'
    | '/callback'
    | '/dashboard'
    | '/discover'
    | '/integrations'
    | '/legal'
    | '/onboard'
    | '/status'
    | '/uplink'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArchitectureRoute: typeof ArchitectureRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LegalRoute: typeof LegalRoute
  OnboardRoute: typeof OnboardRoute
  StatusRoute: typeof StatusRoute
  UplinkRoute: typeof UplinkRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uplink': {
      id: '/uplink'
      path: '/uplink'
      fullPath: '/uplink'
      preLoaderRoute: typeof UplinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArchitectureRoute: ArchitectureRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  IntegrationsRoute: IntegrationsRoute,
  LegalRoute: LegalRoute,
  OnboardRoute: OnboardRoute,
  StatusRoute: StatusRoute,
  UplinkRoute: UplinkRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
