/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetIdTabRouteImport } from './routes/widget.$id.$tab'
import { Route as ChannelTypeTabRouteImport } from './routes/channel.$type.$tab'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIdTabRoute = WidgetIdTabRouteImport.update({
  id: '/widget/$id/$tab',
  path: '/widget/$id/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelTypeTabRoute = ChannelTypeTabRouteImport.update({
  id: '/channel/$type/$tab',
  path: '/channel/$type/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/feed': typeof FeedRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/feed'
    | '/settings'
    | '/support'
    | '/channel/$type/$tab'
    | '/widget/$id/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/feed'
    | '/settings'
    | '/support'
    | '/channel/$type/$tab'
    | '/widget/$id/$tab'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/feed'
    | '/settings'
    | '/support'
    | '/channel/$type/$tab'
    | '/widget/$id/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  FeedRoute: typeof FeedRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  ChannelTypeTabRoute: typeof ChannelTypeTabRoute
  WidgetIdTabRoute: typeof WidgetIdTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$id/$tab': {
      id: '/widget/$id/$tab'
      path: '/widget/$id/$tab'
      fullPath: '/widget/$id/$tab'
      preLoaderRoute: typeof WidgetIdTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$type/$tab': {
      id: '/channel/$type/$tab'
      path: '/channel/$type/$tab'
      fullPath: '/channel/$type/$tab'
      preLoaderRoute: typeof ChannelTypeTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  FeedRoute: FeedRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  ChannelTypeTabRoute: ChannelTypeTabRoute,
  WidgetIdTabRoute: WidgetIdTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
