/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsTabRouteImport } from './routes/settings.$tab'
import { Route as WidgetIdTabRouteImport } from './routes/widget.$id.$tab'
import { Route as ChannelTypeTabRouteImport } from './routes/channel.$type.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTabRoute = SettingsTabRouteImport.update({
  id: '/settings/$tab',
  path: '/settings/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIdTabRoute = WidgetIdTabRouteImport.update({
  id: '/widget/$id/$tab',
  path: '/widget/$id/$tab',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelTypeTabRoute = ChannelTypeTabRouteImport.update({
  id: '/channel/$type/$tab',
  path: '/channel/$type/$tab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/$tab': typeof SettingsTabRoute
  '/channel/$type/$tab': typeof ChannelTypeTabRoute
  '/widget/$id/$tab': typeof WidgetIdTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings/$tab' | '/channel/$type/$tab' | '/widget/$id/$tab'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/$tab' | '/channel/$type/$tab' | '/widget/$id/$tab'
  id:
    | '__root__'
    | '/'
    | '/settings/$tab'
    | '/channel/$type/$tab'
    | '/widget/$id/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsTabRoute: typeof SettingsTabRoute
  ChannelTypeTabRoute: typeof ChannelTypeTabRoute
  WidgetIdTabRoute: typeof WidgetIdTabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$tab': {
      id: '/settings/$tab'
      path: '/settings/$tab'
      fullPath: '/settings/$tab'
      preLoaderRoute: typeof SettingsTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$id/$tab': {
      id: '/widget/$id/$tab'
      path: '/widget/$id/$tab'
      fullPath: '/widget/$id/$tab'
      preLoaderRoute: typeof WidgetIdTabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$type/$tab': {
      id: '/channel/$type/$tab'
      path: '/channel/$type/$tab'
      fullPath: '/channel/$type/$tab'
      preLoaderRoute: typeof ChannelTypeTabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsTabRoute: SettingsTabRoute,
  ChannelTypeTabRoute: ChannelTypeTabRoute,
  WidgetIdTabRoute: WidgetIdTabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
