CREATE TABLE IF NOT EXISTS games (
    id SERIAL PRIMARY KEY,
    league VARCHAR(50) NOT NULL,
    sport VARCHAR(50) NOT NULL DEFAULT '',
    external_game_id VARCHAR(100) NOT NULL,
    link VARCHAR(500),
    home_team_name VARCHAR(100) NOT NULL,
    home_team_logo VARCHAR(500),
    home_team_score INTEGER,
    away_team_name VARCHAR(100) NOT NULL,
    away_team_logo VARCHAR(500),
    away_team_score INTEGER,
    start_time TIMESTAMP WITH TIME ZONE NOT NULL,
    short_detail VARCHAR(200),
    state VARCHAR(50) NOT NULL,
    status_short VARCHAR(20),
    status_long VARCHAR(100),
    timer VARCHAR(20),
    venue VARCHAR(200),
    season VARCHAR(20),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(league, external_game_id)
);

CREATE TABLE IF NOT EXISTS tracked_leagues (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    sport_api VARCHAR(50) NOT NULL DEFAULT '',
    api_host VARCHAR(200) NOT NULL DEFAULT '',
    league_id INTEGER NOT NULL DEFAULT 0,
    category VARCHAR(50) NOT NULL DEFAULT 'Other',
    country VARCHAR(100),
    logo_url VARCHAR(500),
    season VARCHAR(20),
    season_format VARCHAR(20),
    offseason_months INTEGER[],
    is_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
