version: "3.8"

services:
  core-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        COOLIFY_FQDN: core.api.myscrollr.enanimate.dev
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - LOGTO_ENDPOINT=${LOGTO_ENDPOINT:-http://logto-wgooksk48o0gowwk4k8ckc48:3000}
      - LOGTO_JWKS_URL=${LOGTO_JWKS_URL:-http://logto-wgooksk48o0gowwk4k8ckc48:3000/oidc/jwks}
      - LOGTO_URL=https://core.api.myscrollr.enanimate.dev/oidc
      - LOGTO_M2M_RESOURCE=https://core.api.myscrollr.enanimate.dev/api
      - LOGTO_M2M_APP_ID=${LOGTO_M2M_APP_ID:-mock_app_id}
      - LOGTO_M2M_APP_SECRET=${LOGTO_M2M_APP_SECRET:-mock_app_secret}
      - LOGTO_UPLINK_ROLE_ID=${LOGTO_UPLINK_ROLE_ID:-mock_uplink_role}
      - LOGTO_PRO_ROLE_ID=${LOGTO_PRO_ROLE_ID:-mock_pro_role}
      - LOGTO_ULTIMATE_ROLE_ID=${LOGTO_ULTIMATE_ROLE_ID:-mock_ultimate_role}
      - LOGTO_SUPER_USER_ROLE_ID=${LOGTO_SUPER_USER_ROLE_ID:-mock_super_user_role}
      - STRIPE_SECRET_KEY=sk_test_mock
      - STRIPE_API_URL=http://mock-stripe:12111
      - STRIPE_PUBLISHABLE_KEY=pk_test_mock
      - STRIPE_WEBHOOK_SECRET=whsec_test_mock
      - ALLOWED_ORIGINS=https://*.myscrollr.enanimate.dev,http://localhost:5174
    restart: unless-stopped
